# Generated by Django 5.2.4 on 2025-09-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebrba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade_em_serie', models.IntegerField(blank=True, null=True)),
                ('posicao', models.CharField(blank=True, max_length=100)),
                ('nascimento', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sitebrba/img/')),
            ],
        ),
    ]
