# Generated by Django 5.2.4 on 2025-09-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebrba', '0002_personagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personagem',
        ),
        migrations.RemoveField(
            model_name='elenco',
            name='personagem',
        ),
        migrations.AddField(
            model_name='elenco',
            name='nascimento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='elenco',
            name='posicao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='elenco',
            name='idade_em_serie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elenco',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='sitebrba/img/'),
        ),
        migrations.AlterField(
            model_name='elenco',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
