# Generated by Django 5.2.4 on 2025-09-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitebrba', '0003_delete_personagem_remove_elenco_personagem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sobre',
        ),
    ]
